language: python

python:
  - '3.6'

env:
  global:
    - PYTHONWARNINGS="ignore:Unverified HTTPS request"
    - TESTENV_BROKER_URL=https://ws.15xr.msb.oss.cell.vfk.fraunhofer.de/
    - TESTENV_SO_URL=https://so.15xr.msb.oss.cell.vfk.fraunhofer.de/
    - TESTENV_FLOW_URL=https://flow.15xr.msb.oss.cell.vfk.fraunhofer.de/

install:
  - 'pip install pipenv'
  - 'pipenv install --ignore-pipfile --dev'

script: 
  - 'pipenv run python setup.py install'
  - 'pipenv run pytest -s --cov=msb_client'
  - 'pipenv run python setup.py sdist bdist_wheel'

after_success:
  - coveralls
  
deploy:
  provider: pypi # deploys to pypi repo
  user: $PYPI_USER
  password: $PYPI_PASSWORD # to be updated per travis repo
  distributions: "sdist bdist_wheel" # what distributions to upload
  on:
    tags: true # only deploys if a git TAG exists for the commit
    # branch: master # only deploys if branch is master
